const buyingOrganisation = [
  {
    BuyingOrganizationName: "Acumen",
    BuyingOrganizationId: 6,
    IsSelected: false,
    BelongsTo: false,
    IsCIDAccess: false,
    IsTVLiteAccess: true,
    IsTVAccess: true,
    AccessId: 0,
    RoleId: 0
  },
  {
    BuyingOrganizationName: "Acumen Digital",
    BuyingOrganizationId: 9,
    IsSelected: false,
    BelongsTo: false,
    IsCIDAccess: false,
    IsTVLiteAccess: false,
    IsTVAccess: false,
    AccessId: 0,
    RoleId: 0
  },
  {
    BuyingOrganizationName: "Arena Media",
    BuyingOrganizationId: 1,
    IsSelected: false,
    BelongsTo: false,
    IsCIDAccess: true,
    IsTVLiteAccess: true,
    IsTVAccess: true,
    AccessId: 0,
    RoleId: 0
  },
  {
    BuyingOrganizationName: "Forward 1 UK Ltd",
    BuyingOrganizationId: 15,
    IsSelected: false,
    BelongsTo: false,
    IsCIDAccess: true,
    IsTVLiteAccess: false,
    IsTVAccess: true,
    AccessId: 0,
    RoleId: 0
  },
  {
    BuyingOrganizationName: "Fullsix",
    BuyingOrganizationId: 20,
    IsSelected: false,
    BelongsTo: false,
    IsCIDAccess: true,
    IsTVLiteAccess: true,
    IsTVAccess: true,
    AccessId: 0,
    RoleId: 0
  },
  {
    BuyingOrganizationName: "HMI",
    BuyingOrganizationId: 21,
    IsSelected: false,
    BelongsTo: false,
    IsCIDAccess: false,
    IsTVLiteAccess: true,
    IsTVAccess: false,
    AccessId: 0,
    RoleId: 0
  },
  {
    BuyingOrganizationName: "Havas Media",
    BuyingOrganizationId: 2,
    IsSelected: false,
    BelongsTo: false,
    IsCIDAccess: true,
    IsTVLiteAccess: true,
    IsTVAccess: true,
    AccessId: 0,
    RoleId: 0
  },
  {
    BuyingOrganizationName: "LuxHub",
    BuyingOrganizationId: 17,
    IsSelected: false,
    BelongsTo: false,
    IsCIDAccess: true,
    IsTVLiteAccess: true,
    IsTVAccess: true,
    AccessId: 0,
    RoleId: 0
  },
  {
    BuyingOrganizationName: "MI Media",
    BuyingOrganizationId: 7,
    IsSelected: false,
    BelongsTo: false,
    IsCIDAccess: false,
    IsTVLiteAccess: false,
    IsTVAccess: true,
    AccessId: 0,
    RoleId: 0
  },
  {
    BuyingOrganizationName: "Target Live",
    BuyingOrganizationId: 18,
    IsSelected: false,
    BelongsTo: false,
    IsCIDAccess: true,
    IsTVLiteAccess: true,
    IsTVAccess: true,
    AccessId: 0,
    RoleId: 0
  },
  {
    BuyingOrganizationName: "Target Media",
    BuyingOrganizationId: 19,
    IsSelected: false,
    BelongsTo: false,
    IsCIDAccess: true,
    IsTVLiteAccess: true,
    IsTVAccess: true,
    AccessId: 0,
    RoleId: 0
  }
];

const userRole = [
    {
        "OrganisationID": 1,
        "OrganisationName": "Arena Media",
        "IsPrimary": false,
        "RoleId": 1,
        "AccessId": 0,
        "RoleName": "TV Trading Manager",
        "MenuList": null,
        "DefaultURL": "./UserTradingManager",
        "HasRole": false
    },
    {
        "OrganisationID": 2,
        "OrganisationName": "Havas Media",
        "IsPrimary": false,
        "RoleId": 1,
        "AccessId": 0,
        "RoleName": "TV Trading Manager",
        "MenuList": null,
        "DefaultURL": "./UserTradingManager",
        "HasRole": false
    },
    {
        "OrganisationID": 5,
        "OrganisationName": "Smithfield",
        "IsPrimary": false,
        "RoleId": 1,
        "AccessId": 0,
        "RoleName": "TV Trading Manager",
        "MenuList": null,
        "DefaultURL": "./UserTradingManager",
        "HasRole": false
    },
    {
        "OrganisationID": 7,
        "OrganisationName": "MI Media",
        "IsPrimary": false,
        "RoleId": 1,
        "AccessId": 0,
        "RoleName": "TV Trading Manager",
        "MenuList": null,
        "DefaultURL": "./UserTradingManager",
        "HasRole": false
    },
    {
        "OrganisationID": 6,
        "OrganisationName": "Acumen",
        "IsPrimary": false,
        "RoleId": 1,
        "AccessId": 0,
        "RoleName": "TV Trading Manager",
        "MenuList": null,
        "DefaultURL": "./UserTradingManager",
        "HasRole": false
    },
    {
        "OrganisationID": 21,
        "OrganisationName": "HMI",
        "IsPrimary": false,
        "RoleId": 1,
        "AccessId": 0,
        "RoleName": "TV Trading Manager",
        "MenuList": null,
        "DefaultURL": "./UserTradingManager",
        "HasRole": false
    },
    {
        "OrganisationID": 17,
        "OrganisationName": "LuxHub",
        "IsPrimary": false,
        "RoleId": 1,
        "AccessId": 0,
        "RoleName": "TV Trading Manager",
        "MenuList": null,
        "DefaultURL": "./UserTradingManager",
        "HasRole": false
    },
    {
        "OrganisationID": 15,
        "OrganisationName": "Forward 1 UK Ltd",
        "IsPrimary": false,
        "RoleId": 1,
        "AccessId": 0,
        "RoleName": "TV Trading Manager",
        "MenuList": null,
        "DefaultURL": "./UserTradingManager",
        "HasRole": false
    },
    {
        "OrganisationID": 18,
        "OrganisationName": "Target Live",
        "IsPrimary": false,
        "RoleId": 1,
        "AccessId": 0,
        "RoleName": "TV Trading Manager",
        "MenuList": null,
        "DefaultURL": "./UserTradingManager",
        "HasRole": false
    },
    {
        "OrganisationID": 19,
        "OrganisationName": "Target Media",
        "IsPrimary": false,
        "RoleId": 1,
        "AccessId": 0,
        "RoleName": "TV Trading Manager",
        "MenuList": null,
        "DefaultURL": "./UserTradingManager",
        "HasRole": false
    },
    {
        "OrganisationID": 1,
        "OrganisationName": "Arena Media",
        "IsPrimary": false,
        "RoleId": 2,
        "AccessId": 0,
        "RoleName": "TV Manager",
        "MenuList": null,
        "DefaultURL": "./UserManager",
        "HasRole": false
    },
    {
        "OrganisationID": 2,
        "OrganisationName": "Havas Media",
        "IsPrimary": false,
        "RoleId": 2,
        "AccessId": 0,
        "RoleName": "TV Manager",
        "MenuList": null,
        "DefaultURL": "./UserManager",
        "HasRole": false
    },
    {
        "OrganisationID": 5,
        "OrganisationName": "Smithfield",
        "IsPrimary": false,
        "RoleId": 2,
        "AccessId": 0,
        "RoleName": "TV Manager",
        "MenuList": null,
        "DefaultURL": "./UserManager",
        "HasRole": false
    },
    {
        "OrganisationID": 7,
        "OrganisationName": "MI Media",
        "IsPrimary": false,
        "RoleId": 2,
        "AccessId": 0,
        "RoleName": "TV Manager",
        "MenuList": null,
        "DefaultURL": "./UserManager",
        "HasRole": false
    },
    {
        "OrganisationID": 6,
        "OrganisationName": "Acumen",
        "IsPrimary": false,
        "RoleId": 2,
        "AccessId": 0,
        "RoleName": "TV Manager",
        "MenuList": null,
        "DefaultURL": "./UserManager",
        "HasRole": false
    },
    {
        "OrganisationID": 21,
        "OrganisationName": "HMI",
        "IsPrimary": false,
        "RoleId": 2,
        "AccessId": 0,
        "RoleName": "TV Manager",
        "MenuList": null,
        "DefaultURL": "./UserManager",
        "HasRole": false
    },
    {
        "OrganisationID": 17,
        "OrganisationName": "LuxHub",
        "IsPrimary": false,
        "RoleId": 2,
        "AccessId": 0,
        "RoleName": "TV Manager",
        "MenuList": null,
        "DefaultURL": "./UserManager",
        "HasRole": false
    },
    {
        "OrganisationID": 15,
        "OrganisationName": "Forward 1 UK Ltd",
        "IsPrimary": false,
        "RoleId": 2,
        "AccessId": 0,
        "RoleName": "TV Manager",
        "MenuList": null,
        "DefaultURL": "./UserManager",
        "HasRole": false
    },
    {
        "OrganisationID": 18,
        "OrganisationName": "Target Live",
        "IsPrimary": false,
        "RoleId": 2,
        "AccessId": 0,
        "RoleName": "TV Manager",
        "MenuList": null,
        "DefaultURL": "./UserManager",
        "HasRole": false
    },
    {
        "OrganisationID": 19,
        "OrganisationName": "Target Media",
        "IsPrimary": false,
        "RoleId": 2,
        "AccessId": 0,
        "RoleName": "TV Manager",
        "MenuList": null,
        "DefaultURL": "./UserManager",
        "HasRole": false
    },
    {
        "OrganisationID": 1,
        "OrganisationName": "Arena Media",
        "IsPrimary": false,
        "RoleId": 3,
        "AccessId": 0,
        "RoleName": "TV Planner",
        "MenuList": null,
        "DefaultURL": "./UserTVPlanner",
        "HasRole": false
    },
    {
        "OrganisationID": 2,
        "OrganisationName": "Havas Media",
        "IsPrimary": false,
        "RoleId": 3,
        "AccessId": 0,
        "RoleName": "TV Planner",
        "MenuList": null,
        "DefaultURL": "./UserTVPlanner",
        "HasRole": false
    },
    {
        "OrganisationID": 5,
        "OrganisationName": "Smithfield",
        "IsPrimary": false,
        "RoleId": 3,
        "AccessId": 0,
        "RoleName": "TV Planner",
        "MenuList": null,
        "DefaultURL": "./UserTVPlanner",
        "HasRole": false
    },
    {
        "OrganisationID": 7,
        "OrganisationName": "MI Media",
        "IsPrimary": false,
        "RoleId": 3,
        "AccessId": 0,
        "RoleName": "TV Planner",
        "MenuList": null,
        "DefaultURL": "./UserTVPlanner",
        "HasRole": false
    },
    {
        "OrganisationID": 6,
        "IsPrimary": false,
        "OrganisationName": "Acumen",
        "RoleId": 3,
        "AccessId": 0,
        "RoleName": "TV Planner",
        "MenuList": null,
        "DefaultURL": "./UserTVPlanner",
        "HasRole": false
    },
    {
        "OrganisationID": 21,
        "OrganisationName": "HMI",
        "IsPrimary": false,
        "RoleId": 3,
        "AccessId": 0,
        "RoleName": "TV Planner",
        "MenuList": null,
        "DefaultURL": "./UserTVPlanner",
        "HasRole": false
    },
    {
        "OrganisationID": 17,
        "OrganisationName": "LuxHub",
        "IsPrimary": false,
        "RoleId": 3,
        "AccessId": 0,
        "RoleName": "TV Planner",
        "MenuList": null,
        "DefaultURL": "./UserTVPlanner",
        "HasRole": false
    },
    {
        "OrganisationID": 15,
        "OrganisationName": "Forward 1 UK Ltd",
        "IsPrimary": false,
        "RoleId": 3,
        "AccessId": 0,
        "RoleName": "TV Planner",
        "MenuList": null,
        "DefaultURL": "./UserTVPlanner",
        "HasRole": false
    },
    {
        "OrganisationID": 18,
        "OrganisationName": "Target Live",
        "IsPrimary": false,
        "RoleId": 3,
        "AccessId": 0,
        "RoleName": "TV Planner",
        "MenuList": null,
        "DefaultURL": "./UserTVPlanner",
        "HasRole": false
    },
    {
        "OrganisationID": 19,
        "OrganisationName": "Target Media",
        "IsPrimary": false,
        "RoleId": 3,
        "AccessId": 0,
        "RoleName": "TV Planner",
        "MenuList": null,
        "DefaultURL": "./UserTVPlanner",
        "HasRole": false
    },
    {
        "OrganisationID": 1,
        "OrganisationName": "Arena Media",
        "IsPrimary": false,
        "RoleId": 4,
        "AccessId": 0,
        "RoleName": "Billing Officer",
        "MenuList": null,
        "DefaultURL": "./BillingOfficer",
        "HasRole": false
    },
    {
        "OrganisationID": 2,
        "OrganisationName": "Havas Media",
        "IsPrimary": false,
        "RoleId": 4,
        "AccessId": 0,
        "RoleName": "Billing Officer",
        "MenuList": null,
        "DefaultURL": "./BillingOfficer",
        "HasRole": false
    },
    {
        "OrganisationID": 4,
        "OrganisationName": "The Media Network",
        "IsPrimary": false,
        "RoleId": 4,
        "AccessId": 0,
        "RoleName": "Billing Officer",
        "MenuList": null,
        "DefaultURL": "./BillingOfficer",
        "HasRole": false
    },
    {
        "OrganisationID": 5,
        "OrganisationName": "Smithfield",
        "IsPrimary": false,
        "RoleId": 4,
        "AccessId": 0,
        "RoleName": "Billing Officer",
        "MenuList": null,
        "DefaultURL": "./BillingOfficer",
        "HasRole": false
    },
    {
        "OrganisationID": 6,
        "OrganisationName": "Acumen",
        "IsPrimary": false,
        "RoleId": 4,
        "AccessId": 0,
        "RoleName": "Billing Officer",
        "MenuList": null,
        "DefaultURL": "./BillingOfficer",
        "HasRole": false
    },
    {
        "OrganisationID": 7,
        "OrganisationName": "MI Media",
        "IsPrimary": false,
        "RoleId": 4,
        "AccessId": 0,
        "RoleName": "Billing Officer",
        "MenuList": null,
        "DefaultURL": "./BillingOfficer",
        "HasRole": false
    },
    {
        "OrganisationID": 8,
        "OrganisationName": "Pace",
        "IsPrimary": false,
        "RoleId": 4,
        "AccessId": 0,
        "RoleName": "Billing Officer",
        "MenuList": null,
        "DefaultURL": "./BillingOfficer",
        "HasRole": false
    },
    {
        "OrganisationID": 9,
        "OrganisationName": "Acumen Digital",
        "IsPrimary": false,
        "RoleId": 4,
        "AccessId": 0,
        "RoleName": "Billing Officer",
        "MenuList": null,
        "DefaultURL": "./BillingOfficer",
        "HasRole": false
    },
    {
        "OrganisationID": 21,
        "OrganisationName": "HMI",
        "IsPrimary": false,
        "RoleId": 4,
        "AccessId": 0,
        "RoleName": "Billing Officer",
        "MenuList": null,
        "DefaultURL": "./BillingOfficer",
        "HasRole": false
    },
    {
        "OrganisationID": 17,
        "OrganisationName": "LuxHub",
        "IsPrimary": false,
        "RoleId": 4,
        "AccessId": 0,
        "RoleName": "Billing Officer",
        "MenuList": null,
        "DefaultURL": "./BillingOfficer",
        "HasRole": false
    },
    {
        "OrganisationID": 15,
        "OrganisationName": "Forward 1 UK Ltd",
        "IsPrimary": false,
        "RoleId": 4,
        "AccessId": 0,
        "RoleName": "Billing Officer",
        "MenuList": null,
        "DefaultURL": "./BillingOfficer",
        "HasRole": false
    },
    {
        "OrganisationID": 19,
        "OrganisationName": "Target Media",
        "IsPrimary": false,
        "RoleId": 4,
        "AccessId": 0,
        "RoleName": "Billing Officer",
        "MenuList": null,
        "DefaultURL": "./BillingOfficer",
        "HasRole": false
    },
    {
        "OrganisationID": 18,
        "OrganisationName": "Target Live",
        "IsPrimary": false,
        "RoleId": 4,
        "AccessId": 0,
        "RoleName": "Billing Officer",
        "MenuList": null,
        "DefaultURL": "./BillingOfficer",
        "HasRole": false
    },
    {
        "OrganisationID": 20,
        "OrganisationName": "Fullsix",
        "IsPrimary": false,
        "RoleId": 4,
        "AccessId": 0,
        "RoleName": "Billing Officer",
        "MenuList": null,
        "DefaultURL": "./BillingOfficer",
        "HasRole": false
    },
    {
        "OrganisationID": 21,
        "OrganisationName": "HMI",
        "IsPrimary": false,
        "RoleId": 5,
        "AccessId": 0,
        "RoleName": "Admin",
        "MenuList": null,
        "DefaultURL": "./Admin",
        "HasRole": false
    },
    {
        "OrganisationID": 1,
        "OrganisationName": "Arena Media",
        "IsPrimary": false,
        "RoleId": 6,
        "AccessId": 0,
        "RoleName": "MDM Admin",
        "MenuList": null,
        "DefaultURL": "./MDMAdmin",
        "HasRole": false
    },
    {
        "OrganisationID": 2,
        "OrganisationName": "Havas Media",
        "IsPrimary": false,
        "RoleId": 6,
        "AccessId": 0,
        "RoleName": "MDM Admin",
        "MenuList": null,
        "DefaultURL": "./MDMAdmin",
        "HasRole": false
    },
    {
        "OrganisationID": 4,
        "OrganisationName": "The Media Network",
        "IsPrimary": false,
        "RoleId": 6,
        "AccessId": 0,
        "RoleName": "MDM Admin",
        "MenuList": null,
        "DefaultURL": "./MDMAdmin",
        "HasRole": false
    },
    {
        "OrganisationID": 5,
        "OrganisationName": "Smithfield",
        "IsPrimary": false,
        "RoleId": 6,
        "AccessId": 0,
        "RoleName": "MDM Admin",
        "MenuList": null,
        "DefaultURL": "./MDMAdmin",
        "HasRole": false
    },
    {
        "OrganisationID": 6,
        "OrganisationName": "Acumen",
        "IsPrimary": false,
        "RoleId": 6,
        "AccessId": 0,
        "RoleName": "MDM Admin",
        "MenuList": null,
        "DefaultURL": "./MDMAdmin",
        "HasRole": false
    },
    {
        "OrganisationID": 7,
        "OrganisationName": "MI Media",
        "IsPrimary": false,
        "RoleId": 6,
        "AccessId": 0,
        "RoleName": "MDM Admin",
        "MenuList": null,
        "DefaultURL": "./MDMAdmin",
        "HasRole": false
    },
    {
        "OrganisationID": 8,
        "OrganisationName": "Pace",
        "IsPrimary": false,
        "RoleId": 6,
        "AccessId": 0,
        "RoleName": "MDM Admin",
        "MenuList": null,
        "DefaultURL": "./MDMAdmin",
        "HasRole": false
    },
    {
        "OrganisationID": 9,
        "OrganisationName": "Acumen Digital",
        "IsPrimary": false,
        "RoleId": 6,
        "AccessId": 0,
        "RoleName": "MDM Admin",
        "MenuList": null,
        "DefaultURL": "./MDMAdmin",
        "HasRole": false
    },
    {
        "OrganisationID": 21,
        "OrganisationName": "HMI",
        "IsPrimary": false,
        "RoleId": 6,
        "AccessId": 0,
        "RoleName": "MDM Admin",
        "MenuList": null,
        "DefaultURL": "./MDMAdmin",
        "HasRole": false
    },
    {
        "OrganisationID": 17,
        "OrganisationName": "LuxHub",
        "IsPrimary": false,
        "RoleId": 6,
        "AccessId": 0,
        "RoleName": "MDM Admin",
        "MenuList": null,
        "DefaultURL": "./MDMAdmin",
        "HasRole": false
    },
    {
        "OrganisationID": 15,
        "OrganisationName": "Forward 1 UK Ltd",
        "IsPrimary": false,
        "RoleId": 6,
        "AccessId": 0,
        "RoleName": "MDM Admin",
        "MenuList": null,
        "DefaultURL": "./MDMAdmin",
        "HasRole": false
    },
    {
        "OrganisationID": 19,
        "OrganisationName": "Target Media",
        "IsPrimary": false,
        "RoleId": 6,
        "AccessId": 0,
        "RoleName": "MDM Admin",
        "MenuList": null,
        "DefaultURL": "./MDMAdmin",
        "HasRole": false
    },
    {
        "OrganisationID": 18,
        "OrganisationName": "Target Live",
        "IsPrimary": false,
        "RoleId": 6,
        "AccessId": 0,
        "RoleName": "MDM Admin",
        "MenuList": null,
        "DefaultURL": "./MDMAdmin",
        "HasRole": false
    },
    {
        "OrganisationID": 20,
        "OrganisationName": "Fullsix",
        "IsPrimary": false,
        "RoleId": 6,
        "AccessId": 0,
        "RoleName": "MDM Admin",
        "MenuList": null,
        "DefaultURL": "./MDMAdmin",
        "HasRole": false
    },
    {
        "OrganisationID": 1,
        "OrganisationName": "Arena Media",
        "IsPrimary": false,
        "RoleId": 7,
        "AccessId": 0,
        "RoleName": "Account Manager",
        "MenuList": null,
        "DefaultURL": "./AccountManager",
        "HasRole": false
    },
    {
        "OrganisationID": 2,
        "OrganisationName": "Havas Media",
        "IsPrimary": false,
        "RoleId": 7,
        "AccessId": 0,
        "RoleName": "Account Manager",
        "MenuList": null,
        "DefaultURL": "./AccountManager",
        "HasRole": false
    },
    {
        "OrganisationID": 4,
        "OrganisationName": "The Media Network",
        "IsPrimary": false,
        "RoleId": 7,
        "AccessId": 0,
        "RoleName": "Account Manager",
        "MenuList": null,
        "DefaultURL": "./AccountManager",
        "HasRole": false
    },
    {
        "OrganisationID": 5,
        "OrganisationName": "Smithfield",
        "IsPrimary": false,
        "RoleId": 7,
        "AccessId": 0,
        "RoleName": "Account Manager",
        "MenuList": null,
        "DefaultURL": "./AccountManager",
        "HasRole": false
    },
    {
        "OrganisationID": 6,
        "OrganisationName": "Acumen",
        "IsPrimary": false,
        "RoleId": 7,
        "AccessId": 0,
        "RoleName": "Account Manager",
        "MenuList": null,
        "DefaultURL": "./AccountManager",
        "HasRole": false
    },
    {
        "OrganisationID": 7,
        "OrganisationName": "MI Media",
        "IsPrimary": false,
        "RoleId": 7,
        "AccessId": 0,
        "RoleName": "Account Manager",
        "MenuList": null,
        "DefaultURL": "./AccountManager",
        "HasRole": false
    },
    {
        "OrganisationID": 8,
        "OrganisationName": "Pace",
        "IsPrimary": false,
        "RoleId": 7,
        "AccessId": 0,
        "RoleName": "Account Manager",
        "MenuList": null,
        "DefaultURL": "./AccountManager",
        "HasRole": false
    },
    {
        "OrganisationID": 9,
        "OrganisationName": "Acumen Digital",
        "IsPrimary": false,
        "RoleId": 7,
        "AccessId": 0,
        "RoleName": "Account Manager",
        "MenuList": null,
        "DefaultURL": "./AccountManager",
        "HasRole": false
    },
    {
        "OrganisationID": 21,
        "OrganisationName": "HMI",
        "IsPrimary": false,
        "RoleId": 7,
        "AccessId": 0,
        "RoleName": "Account Manager",
        "MenuList": null,
        "DefaultURL": "./AccountManager",
        "HasRole": false
    },
    {
        "OrganisationID": 17,
        "OrganisationName": "LuxHub",
        "IsPrimary": false,
        "RoleId": 7,
        "AccessId": 0,
        "RoleName": "Account Manager",
        "MenuList": null,
        "DefaultURL": "./AccountManager",
        "HasRole": false
    },
    {
        "OrganisationID": 15,
        "OrganisationName": "Forward 1 UK Ltd",
        "IsPrimary": false,
        "RoleId": 7,
        "AccessId": 0,
        "RoleName": "Account Manager",
        "MenuList": null,
        "DefaultURL": "./AccountManager",
        "HasRole": false
    },
    {
        "OrganisationID": 19,
        "OrganisationName": "Target Media",
        "IsPrimary": false,
        "RoleId": 7,
        "AccessId": 0,
        "RoleName": "Account Manager",
        "MenuList": null,
        "DefaultURL": "./AccountManager",
        "HasRole": false
    },
    {
        "OrganisationID": 18,
        "OrganisationName": "Target Live",
        "IsPrimary": false,
        "RoleId": 7,
        "AccessId": 0,
        "RoleName": "Account Manager",
        "MenuList": null,
        "DefaultURL": "./AccountManager",
        "HasRole": false
    },
    {
        "OrganisationID": 20,
        "OrganisationName": "Fullsix",
        "IsPrimary": false,
        "RoleId": 7,
        "AccessId": 0,
        "RoleName": "Account Manager",
        "MenuList": null,
        "DefaultURL": "./AccountManager",
        "HasRole": false
    },
    {
        "OrganisationID": 1,
        "OrganisationName": "Arena Media",
        "IsPrimary": false,
        "RoleId": 8,
        "AccessId": 0,
        "RoleName": "Trading Manager",
        "MenuList": null,
        "DefaultURL": "./TradingManager",
        "HasRole": false
    },
    {
        "OrganisationID": 2,
        "OrganisationName": "Havas Media",
        "IsPrimary": false,
        "RoleId": 8,
        "AccessId": 0,
        "RoleName": "Trading Manager",
        "MenuList": null,
        "DefaultURL": "./TradingManager",
        "HasRole": false
    },
    {
        "OrganisationID": 4,
        "OrganisationName": "The Media Network",
        "IsPrimary": false,
        "RoleId": 8,
        "AccessId": 0,
        "RoleName": "Trading Manager",
        "MenuList": null,
        "DefaultURL": "./TradingManager",
        "HasRole": false
    },
    {
        "OrganisationID": 5,
        "OrganisationName": "Smithfield",
        "IsPrimary": false,
        "RoleId": 8,
        "AccessId": 0,
        "RoleName": "Trading Manager",
        "MenuList": null,
        "DefaultURL": "./TradingManager",
        "HasRole": false
    },
    {
        "OrganisationID": 6,
        "OrganisationName": "Acumen",
        "IsPrimary": false,
        "RoleId": 8,
        "AccessId": 0,
        "RoleName": "Trading Manager",
        "MenuList": null,
        "DefaultURL": "./TradingManager",
        "HasRole": false
    },
    {
        "OrganisationID": 7,
        "OrganisationName": "MI Media",
        "IsPrimary": false,
        "RoleId": 8,
        "AccessId": 0,
        "RoleName": "Trading Manager",
        "MenuList": null,
        "DefaultURL": "./TradingManager",
        "HasRole": false
    },
    {
        "OrganisationID": 8,
        "OrganisationName": "Pace",
        "IsPrimary": false,
        "RoleId": 8,
        "AccessId": 0,
        "RoleName": "Trading Manager",
        "MenuList": null,
        "DefaultURL": "./TradingManager",
        "HasRole": false
    },
    {
        "OrganisationID": 9,
        "OrganisationName": "Acumen Digital",
        "IsPrimary": false,
        "RoleId": 8,
        "AccessId": 0,
        "RoleName": "Trading Manager",
        "MenuList": null,
        "DefaultURL": "./TradingManager",
        "HasRole": false
    },
    {
        "OrganisationID": 21,
        "OrganisationName": "HMI",
        "IsPrimary": false,
        "RoleId": 8,
        "AccessId": 0,
        "RoleName": "Trading Manager",
        "MenuList": null,
        "DefaultURL": "./TradingManager",
        "HasRole": false
    },
    {
        "OrganisationID": 17,
        "OrganisationName": "LuxHub",
        "IsPrimary": false,
        "RoleId": 8,
        "AccessId": 0,
        "RoleName": "Trading Manager",
        "MenuList": null,
        "DefaultURL": "./TradingManager",
        "HasRole": false
    },
    {
        "OrganisationID": 15,
        "OrganisationName": "Forward 1 UK Ltd",
        "IsPrimary": false,
        "RoleId": 8,
        "AccessId": 0,
        "RoleName": "Trading Manager",
        "MenuList": null,
        "DefaultURL": "./TradingManager",
        "HasRole": false
    },
    {
        "OrganisationID": 19,
        "OrganisationName": "Target Media",
        "IsPrimary": false,
        "RoleId": 8,
        "AccessId": 0,
        "RoleName": "Trading Manager",
        "MenuList": null,
        "DefaultURL": "./TradingManager",
        "HasRole": false
    },
    {
        "OrganisationID": 18,
        "OrganisationName": "Target Live",
        "IsPrimary": false,
        "RoleId": 8,
        "AccessId": 0,
        "RoleName": "Trading Manager",
        "MenuList": null,
        "DefaultURL": "./TradingManager",
        "HasRole": false
    },
    {
        "OrganisationID": 20,
        "OrganisationName": "Fullsix",
        "IsPrimary": false,
        "RoleId": 8,
        "AccessId": 0,
        "RoleName": "Trading Manager",
        "MenuList": null,
        "DefaultURL": "./TradingManager",
        "HasRole": false
    },
    {
        "OrganisationID": 1,
        "OrganisationName": "Arena Media",
        "IsPrimary": false,
        "RoleId": 9,
        "AccessId": 0,
        "RoleName": "Business Director",
        "MenuList": null,
        "DefaultURL": "./BusinessDirector",
        "HasRole": false
    },
    {
        "OrganisationID": 2,
        "OrganisationName": "Havas Media",
        "IsPrimary": false,
        "RoleId": 9,
        "AccessId": 0,
        "RoleName": "Business Director",
        "MenuList": null,
        "DefaultURL": "./BusinessDirector",
        "HasRole": false
    },
    {
        "OrganisationID": 4,
        "OrganisationName": "The Media Network",
        "IsPrimary": false,
        "RoleId": 9,
        "AccessId": 0,
        "RoleName": "Business Director",
        "MenuList": null,
        "DefaultURL": "./BusinessDirector",
        "HasRole": false
    },
    {
        "OrganisationID": 5,
        "OrganisationName": "Smithfield",
        "IsPrimary": false,
        "RoleId": 9,
        "AccessId": 0,
        "RoleName": "Business Director",
        "MenuList": null,
        "DefaultURL": "./BusinessDirector",
        "HasRole": false
    },
    {
        "OrganisationID": 6,
        "OrganisationName": "Acumen",
        "IsPrimary": false,
        "RoleId": 9,
        "AccessId": 0,
        "RoleName": "Business Director",
        "MenuList": null,
        "DefaultURL": "./BusinessDirector",
        "HasRole": false
    },
    {
        "OrganisationID": 7,
        "OrganisationName": "MI Media",
        "IsPrimary": false,
        "RoleId": 9,
        "AccessId": 0,
        "RoleName": "Business Director",
        "MenuList": null,
        "DefaultURL": "./BusinessDirector",
        "HasRole": false
    },
    {
        "OrganisationID": 8,
        "OrganisationName": "Pace",
        "IsPrimary": false,
        "RoleId": 9,
        "AccessId": 0,
        "RoleName": "Business Director",
        "MenuList": null,
        "DefaultURL": "./BusinessDirector",
        "HasRole": false
    },
    {
        "OrganisationID": 9,
        "OrganisationName": "Acumen Digital",
        "IsPrimary": false,
        "RoleId": 9,
        "AccessId": 0,
        "RoleName": "Business Director",
        "MenuList": null,
        "DefaultURL": "./BusinessDirector",
        "HasRole": false
    },
    {
        "OrganisationID": 21,
        "OrganisationName": "HMI",
        "IsPrimary": false,
        "RoleId": 9,
        "AccessId": 0,
        "RoleName": "Business Director",
        "MenuList": null,
        "DefaultURL": "./BusinessDirector",
        "HasRole": false
    },
    {
        "OrganisationID": 17,
        "OrganisationName": "LuxHub",
        "IsPrimary": false,
        "RoleId": 9,
        "AccessId": 0,
        "RoleName": "Business Director",
        "MenuList": null,
        "DefaultURL": "./BusinessDirector",
        "HasRole": false
    },
    {
        "OrganisationID": 15,
        "OrganisationName": "Forward 1 UK Ltd",
        "IsPrimary": false,
        "RoleId": 9,
        "AccessId": 0,
        "RoleName": "Business Director",
        "MenuList": null,
        "DefaultURL": "./BusinessDirector",
        "HasRole": false
    },
    {
        "OrganisationID": 19,
        "OrganisationName": "Target Media",
        "IsPrimary": false,
        "RoleId": 9,
        "AccessId": 0,
        "RoleName": "Business Director",
        "MenuList": null,
        "DefaultURL": "./BusinessDirector",
        "HasRole": false
    },
    {
        "OrganisationID": 18,
        "OrganisationName": "Target Live",
        "IsPrimary": false,
        "RoleId": 9,
        "AccessId": 0,
        "RoleName": "Business Director",
        "MenuList": null,
        "DefaultURL": "./BusinessDirector",
        "HasRole": false
    },
    {
        "OrganisationID": 20,
        "OrganisationName": "Fullsix",
        "IsPrimary": false,
        "RoleId": 9,
        "AccessId": 0,
        "RoleName": "Business Director",
        "MenuList": null,
        "DefaultURL": "./BusinessDirector",
        "HasRole": false
    },
    {
        "OrganisationID": 1,
        "OrganisationName": "Arena Media",
        "IsPrimary": false,
        "RoleId": 10,
        "AccessId": 0,
        "RoleName": "Planner Buyer",
        "MenuList": null,
        "DefaultURL": "./PlannerBuyer",
        "HasRole": false
    },
    {
        "OrganisationID": 2,
        "OrganisationName": "Havas Media",
        "IsPrimary": false,
        "RoleId": 10,
        "AccessId": 0,
        "RoleName": "Planner Buyer",
        "MenuList": null,
        "DefaultURL": "./PlannerBuyer",
        "HasRole": false
    },
    {
        "OrganisationID": 4,
        "OrganisationName": "The Media Network",
        "IsPrimary": false,
        "RoleId": 10,
        "AccessId": 0,
        "RoleName": "Planner Buyer",
        "MenuList": null,
        "DefaultURL": "./PlannerBuyer",
        "HasRole": false
    },
    {
        "OrganisationID": 5,
        "OrganisationName": "Smithfield",
        "IsPrimary": false,
        "RoleId": 10,
        "AccessId": 0,
        "RoleName": "Planner Buyer",
        "MenuList": null,
        "DefaultURL": "./PlannerBuyer",
        "HasRole": false
    },
    {
        "OrganisationID": 6,
        "OrganisationName": "Acumen",
        "IsPrimary": false,
        "RoleId": 10,
        "AccessId": 0,
        "RoleName": "Planner Buyer",
        "MenuList": null,
        "DefaultURL": "./PlannerBuyer",
        "HasRole": false
    },
    {
        "OrganisationID": 7,
        "OrganisationName": "MI Media",
        "IsPrimary": false,
        "RoleId": 10,
        "AccessId": 0,
        "RoleName": "Planner Buyer",
        "MenuList": null,
        "DefaultURL": "./PlannerBuyer",
        "HasRole": false
    },
    {
        "OrganisationID": 8,
        "OrganisationName": "Pace",
        "IsPrimary": false,
        "RoleId": 10,
        "AccessId": 0,
        "RoleName": "Planner Buyer",
        "MenuList": null,
        "DefaultURL": "./PlannerBuyer",
        "HasRole": false
    },
    {
        "OrganisationID": 9,
        "OrganisationName": "Acumen Digital",
        "IsPrimary": false,
        "RoleId": 10,
        "AccessId": 0,
        "RoleName": "Planner Buyer",
        "MenuList": null,
        "DefaultURL": "./PlannerBuyer",
        "HasRole": false
    },
    {
        "OrganisationID": 21,
        "OrganisationName": "HMI",
        "IsPrimary": false,
        "RoleId": 10,
        "AccessId": 0,
        "RoleName": "Planner Buyer",
        "MenuList": null,
        "DefaultURL": "./PlannerBuyer",
        "HasRole": false
    },
    {
        "OrganisationID": 17,
        "OrganisationName": "LuxHub",
        "IsPrimary": false,
        "RoleId": 10,
        "AccessId": 0,
        "RoleName": "Planner Buyer",
        "MenuList": null,
        "DefaultURL": "./PlannerBuyer",
        "HasRole": false
    },
    {
        "OrganisationID": 15,
        "OrganisationName": "Forward 1 UK Ltd",
        "IsPrimary": false,
        "RoleId": 10,
        "AccessId": 0,
        "RoleName": "Planner Buyer",
        "MenuList": null,
        "DefaultURL": "./PlannerBuyer",
        "HasRole": false
    },
    {
        "OrganisationID": 19,
        "OrganisationName": "Target Media",
        "IsPrimary": false,
        "RoleId": 10,
        "AccessId": 0,
        "RoleName": "Planner Buyer",
        "MenuList": null,
        "DefaultURL": "./PlannerBuyer",
        "HasRole": false
    },
    {
        "OrganisationID": 18,
        "OrganisationName": "Target Live",
        "IsPrimary": false,
        "RoleId": 10,
        "AccessId": 0,
        "RoleName": "Planner Buyer",
        "MenuList": null,
        "DefaultURL": "./PlannerBuyer",
        "HasRole": false
    },
    {
        "OrganisationID": 20,
        "OrganisationName": "Fullsix",
        "IsPrimary": false,
        "RoleId": 10,
        "AccessId": 0,
        "RoleName": "Planner Buyer",
        "MenuList": null,
        "DefaultURL": "./PlannerBuyer",
        "HasRole": false
    },
    {
        "OrganisationID": 1,
        "OrganisationName": "Arena Media",
        "IsPrimary": false,
        "RoleId": 11,
        "AccessId": 0,
        "RoleName": "Finance Controller",
        "MenuList": null,
        "DefaultURL": "./FinanceController",
        "HasRole": false
    },
    {
        "OrganisationID": 2,
        "OrganisationName": "Havas Media",
        "IsPrimary": false,
        "RoleId": 11,
        "AccessId": 0,
        "RoleName": "Finance Controller",
        "MenuList": null,
        "DefaultURL": "./FinanceController",
        "HasRole": false
    },
    {
        "OrganisationID": 4,
        "OrganisationName": "The Media Network",
        "IsPrimary": false,
        "RoleId": 11,
        "AccessId": 0,
        "RoleName": "Finance Controller",
        "MenuList": null,
        "DefaultURL": "./FinanceController",
        "HasRole": false
    },
    {
        "OrganisationID": 5,
        "OrganisationName": "Smithfield",
        "IsPrimary": false,
        "RoleId": 11,
        "AccessId": 0,
        "RoleName": "Finance Controller",
        "MenuList": null,
        "DefaultURL": "./FinanceController",
        "HasRole": false
    },
    {
        "OrganisationID": 6,
        "OrganisationName": "Acumen",
        "IsPrimary": false,
        "RoleId": 11,
        "AccessId": 0,
        "RoleName": "Finance Controller",
        "MenuList": null,
        "DefaultURL": "./FinanceController",
        "HasRole": false
    },
    {
        "OrganisationID": 7,
        "OrganisationName": "MI Media",
        "IsPrimary": false,
        "RoleId": 11,
        "AccessId": 0,
        "RoleName": "Finance Controller",
        "MenuList": null,
        "DefaultURL": "./FinanceController",
        "HasRole": false
    },
    {
        "OrganisationID": 8,
        "OrganisationName": "Pace",
        "IsPrimary": false,
        "RoleId": 11,
        "AccessId": 0,
        "RoleName": "Finance Controller",
        "MenuList": null,
        "DefaultURL": "./FinanceController",
        "HasRole": false
    },
    {
        "OrganisationID": 9,
        "OrganisationName": "Acumen Digital",
        "IsPrimary": false,
        "RoleId": 11,
        "AccessId": 0,
        "RoleName": "Finance Controller",
        "MenuList": null,
        "DefaultURL": "./FinanceController",
        "HasRole": false
    },
    {
        "OrganisationID": 21,
        "OrganisationName": "HMI",
        "IsPrimary": false,
        "RoleId": 11,
        "AccessId": 0,
        "RoleName": "Finance Controller",
        "MenuList": null,
        "DefaultURL": "./FinanceController",
        "HasRole": false
    },
    {
        "OrganisationID": 17,
        "OrganisationName": "LuxHub",
        "IsPrimary": false,
        "RoleId": 11,
        "AccessId": 0,
        "RoleName": "Finance Controller",
        "MenuList": null,
        "DefaultURL": "./FinanceController",
        "HasRole": false
    },
    {
        "OrganisationID": 15,
        "OrganisationName": "Forward 1 UK Ltd",
        "IsPrimary": false,
        "RoleId": 11,
        "AccessId": 0,
        "RoleName": "Finance Controller",
        "MenuList": null,
        "DefaultURL": "./FinanceController",
        "HasRole": false
    },
    {
        "OrganisationID": 19,
        "OrganisationName": "Target Media",
        "IsPrimary": false,
        "RoleId": 11,
        "AccessId": 0,
        "RoleName": "Finance Controller",
        "MenuList": null,
        "DefaultURL": "./FinanceController",
        "HasRole": false
    },
    {
        "OrganisationID": 18,
        "OrganisationName": "Target Live",
        "IsPrimary": false,
        "RoleId": 11,
        "AccessId": 0,
        "RoleName": "Finance Controller",
        "MenuList": null,
        "DefaultURL": "./FinanceController",
        "HasRole": false
    },
    {
        "OrganisationID": 20,
        "OrganisationName": "Fullsix",
        "IsPrimary": false,
        "RoleId": 11,
        "AccessId": 0,
        "RoleName": "Finance Controller",
        "MenuList": null,
        "DefaultURL": "./FinanceController",
        "HasRole": false
    },
    {
        "OrganisationID": 21,
        "OrganisationName": "HMI",
        "IsPrimary": false,
        "RoleId": 12,
        "AccessId": 0,
        "RoleName": "TV Manager Lite",
        "MenuList": null,
        "DefaultURL": "./TV Manager Lite",
        "HasRole": false
    },
    {
        "OrganisationID": 6,
        "OrganisationName": "Acumen",
        "IsPrimary": false,
        "RoleId": 12,
        "AccessId": 0,
        "RoleName": "TV Manager Lite",
        "MenuList": null,
        "DefaultURL": "./TV Manager Lite",
        "HasRole": false
    },
    {
        "OrganisationID": 1,
        "OrganisationName": "Arena Media",
        "IsPrimary": false,
        "RoleId": 12,
        "AccessId": 0,
        "RoleName": "TV Manager Lite",
        "MenuList": null,
        "DefaultURL": "./TV Manager Lite",
        "HasRole": false
    },
    {
        "OrganisationID": 20,
        "OrganisationName": "Fullsix",
        "IsPrimary": false,
        "RoleId": 12,
        "AccessId": 0,
        "RoleName": "TV Manager Lite",
        "MenuList": null,
        "DefaultURL": "./TV Manager Lite",
        "HasRole": false
    },
    {
        "OrganisationID": 5,
        "OrganisationName": "Smithfield",
        "IsPrimary": false,
        "RoleId": 12,
        "AccessId": 0,
        "RoleName": "TV Manager Lite",
        "MenuList": null,
        "DefaultURL": "./TV Manager Lite",
        "HasRole": false
    },
    {
        "OrganisationID": 19,
        "OrganisationName": "Target Media",
        "IsPrimary": false,
        "RoleId": 12,
        "AccessId": 0,
        "RoleName": "TV Manager Lite",
        "MenuList": null,
        "DefaultURL": "./TV Manager Lite",
        "HasRole": false
    },
    {
        "OrganisationID": 17,
        "OrganisationName": "LuxHub",
        "IsPrimary": false,
        "RoleId": 12,
        "AccessId": 0,
        "RoleName": "TV Manager Lite",
        "MenuList": null,
        "DefaultURL": "./TV Manager Lite",
        "HasRole": false
    },
    {
        "OrganisationID": 2,
        "OrganisationName": "Havas Media",
        "IsPrimary": false,
        "RoleId": 12,
        "AccessId": 0,
        "RoleName": "TV Manager Lite",
        "MenuList": null,
        "DefaultURL": "./TV Manager Lite",
        "HasRole": false
    },
    {
        "OrganisationID": 18,
        "OrganisationName": "Target Live",
        "IsPrimary": false,
        "RoleId": 12,
        "AccessId": 0,
        "RoleName": "TV Manager Lite",
        "MenuList": null,
        "DefaultURL": "./TV Manager Lite",
        "HasRole": false
    },
    {
        "OrganisationID": 17,
        "OrganisationName": "LuxHub",
        "IsPrimary": false,
        "RoleId": 13,
        "AccessId": 0,
        "RoleName": "MDM View",
        "MenuList": null,
        "DefaultURL": "./MDM View",
        "HasRole": false
    },
    {
        "OrganisationID": 18,
        "OrganisationName": "Target Live",
        "IsPrimary": false,
        "RoleId": 13,
        "AccessId": 0,
        "RoleName": "MDM View",
        "MenuList": null,
        "DefaultURL": "./MDM View",
        "HasRole": false
    },
    {
        "OrganisationID": 19,
        "OrganisationName": "Target Media",
        "IsPrimary": false,
        "RoleId": 13,
        "AccessId": 0,
        "RoleName": "MDM View",
        "MenuList": null,
        "DefaultURL": "./MDM View",
        "HasRole": false
    },
    {
        "OrganisationID": 20,
        "OrganisationName": "Fullsix",
        "IsPrimary": false,
        "RoleId": 13,
        "AccessId": 0,
        "RoleName": "MDM View",
        "MenuList": null,
        "DefaultURL": "./MDM View",
        "HasRole": false
    },
    {
        "OrganisationID": 15,
        "OrganisationName": "Forward 1 UK Ltd",
        "IsPrimary": false,
        "RoleId": 13,
        "AccessId": 0,
        "RoleName": "MDM View",
        "MenuList": null,
        "DefaultURL": "./MDM View",
        "HasRole": false
    },
    {
        "OrganisationID": 9,
        "OrganisationName": "Acumen Digital",
        "IsPrimary": false,
        "RoleId": 13,
        "AccessId": 0,
        "RoleName": "MDM View",
        "MenuList": null,
        "DefaultURL": "./MDM View",
        "HasRole": false
    },
    {
        "OrganisationID": 8,
        "OrganisationName": "Pace",
        "IsPrimary": false,
        "RoleId": 13,
        "AccessId": 0,
        "RoleName": "MDM View",
        "MenuList": null,
        "DefaultURL": "./MDM View",
        "HasRole": false
    },
    {
        "OrganisationID": 7,
        "OrganisationName": "MI Media",
        "IsPrimary": false,
        "RoleId": 13,
        "AccessId": 0,
        "RoleName": "MDM View",
        "MenuList": null,
        "DefaultURL": "./MDM View",
        "HasRole": false
    },
    {
        "OrganisationID": 6,
        "OrganisationName": "Acumen",
        "IsPrimary": false,
        "RoleId": 13,
        "AccessId": 0,
        "RoleName": "MDM View",
        "MenuList": null,
        "DefaultURL": "./MDM View",
        "HasRole": false
    },
    {
        "OrganisationID": 5,
        "OrganisationName": "Smithfield",
        "IsPrimary": false,
        "RoleId": 13,
        "AccessId": 0,
        "RoleName": "MDM View",
        "MenuList": null,
        "DefaultURL": "./MDM View",
        "HasRole": false
    },
    {
        "OrganisationID": 21,
        "OrganisationName": "HMI",
        "IsPrimary": false,
        "RoleId": 13,
        "AccessId": 0,
        "RoleName": "MDM View",
        "MenuList": null,
        "DefaultURL": "./MDM View",
        "HasRole": false
    },
    {
        "OrganisationID": 2,
        "OrganisationName": "Havas Media",
        "IsPrimary": false,
        "RoleId": 13,
        "AccessId": 0,
        "RoleName": "MDM View",
        "MenuList": null,
        "DefaultURL": "./MDM View",
        "HasRole": false
    },
    {
        "OrganisationID": 1,
        "OrganisationName": "Arena Media",
        "IsPrimary": false,
        "RoleId": 13,
        "AccessId": 0,
        "RoleName": "MDM View",
        "MenuList": null,
        "DefaultURL": "./MDM View",
        "HasRole": false
    },
    {
        "OrganisationID": 4,
        "OrganisationName": "The Media Network",
        "IsPrimary": false,
        "RoleId": 13,
        "AccessId": 0,
        "RoleName": "MDM View",
        "MenuList": null,
        "DefaultURL": "./MDM View",
        "HasRole": false
    }
]


// CID ROles
const Roles = 
{ 
    "MMSRoles":[ 
       { 
          "OrganisationID":0,
          "OrganisationName":null,
          "IsPrimary":false,
          "RoleId":1,
          "AccessId":-1,
          "RoleName":"TV Trading Manager",
          "MenuList":null,
          "DefaultURL":"./UserTradingManager",
          "HasRole":false
       },
       { 
          "OrganisationID":0,
          "OrganisationName":null,
          "IsPrimary":false,
          "RoleId":2,
          "AccessId":-1,
          "RoleName":"TV Manager",
          "MenuList":null,
          "DefaultURL":"./UserManager",
          "HasRole":false
       },
       { 
          "OrganisationID":0,
          "OrganisationName":null,
          "IsPrimary":false,
          "RoleId":3,
          "AccessId":-1,
          "RoleName":"TV Planner",
          "MenuList":null,
          "DefaultURL":"./UserTVPlanner",
          "HasRole":false
       },
       { 
          "OrganisationID":0,
          "OrganisationName":null,
          "IsPrimary":false,
          "RoleId":4,
          "AccessId":-1,
          "RoleName":"Billing Officer",
          "MenuList":null,
          "DefaultURL":"./BillingOfficer",
          "HasRole":false
       },
       { 
          "OrganisationID":0,
          "OrganisationName":null,
          "IsPrimary":false,
          "RoleId":6,
          "AccessId":-1,
          "RoleName":"MDM Admin",
          "MenuList":null,
          "DefaultURL":"./MDMAdmin",
          "HasRole":false
       },
       { 
          "OrganisationID":0,
          "OrganisationName":null,
          "IsPrimary":false,
          "RoleId":7,
          "AccessId":-1,
          "RoleName":"Account Manager",
          "MenuList":null,
          "DefaultURL":"./AccountManager",
          "HasRole":false
       },
       { 
          "OrganisationID":0,
          "OrganisationName":null,
          "IsPrimary":false,
          "RoleId":8,
          "AccessId":-1,
          "RoleName":"Trading Manager",
          "MenuList":null,
          "DefaultURL":"./TradingManager",
          "HasRole":false
       },
       { 
          "OrganisationID":0,
          "OrganisationName":null,
          "IsPrimary":false,
          "RoleId":9,
          "AccessId":-1,
          "RoleName":"Business Director",
          "MenuList":null,
          "DefaultURL":"./BusinessDirector",
          "HasRole":false
       },
       { 
          "OrganisationID":0,
          "OrganisationName":null,
          "IsPrimary":false,
          "RoleId":10,
          "AccessId":-1,
          "RoleName":"Planner Buyer",
          "MenuList":null,
          "DefaultURL":"./PlannerBuyer",
          "HasRole":false
       },
       { 
          "OrganisationID":0,
          "OrganisationName":null,
          "IsPrimary":false,
          "RoleId":11,
          "AccessId":-1,
          "RoleName":"Finance Controller",
          "MenuList":null,
          "DefaultURL":"./FinanceController",
          "HasRole":false
       },
       { 
          "OrganisationID":0,
          "OrganisationName":null,
          "IsPrimary":false,
          "RoleId":12,
          "AccessId":-1,
          "RoleName":"TV Manager Lite",
          "MenuList":null,
          "DefaultURL":"./TV Manager Lite",
          "HasRole":false
       },
       { 
          "OrganisationID":0,
          "OrganisationName":null,
          "IsPrimary":false,
          "RoleId":13,
          "AccessId":-1,
          "RoleName":"MDM View",
          "MenuList":null,
          "DefaultURL":"./MDM View",
          "HasRole":false
       }
    ],
    "CIDRoles":[ 
       { 
          "OrganisationID":0,
          "OrganisationName":null,
          "IsPrimary":false,
          "RoleId":1,
          "AccessId":-1,
          "RoleName":"CID Manager",
          "MenuList":null,
          "DefaultURL":null,
          "HasRole":false
       },
       { 
          "OrganisationID":0,
          "OrganisationName":null,
          "IsPrimary":false,
          "RoleId":2,
          "AccessId":-1,
          "RoleName":"GBD",
          "MenuList":null,
          "DefaultURL":null,
          "HasRole":false
       },
       { 
          "OrganisationID":0,
          "OrganisationName":null,
          "IsPrimary":false,
          "RoleId":3,
          "AccessId":-1,
          "RoleName":"Senior Management",
          "MenuList":null,
          "DefaultURL":null,
          "HasRole":false
       },
       { 
          "OrganisationID":0,
          "OrganisationName":null,
          "IsPrimary":false,
          "RoleId":4,
          "AccessId":-1,
          "RoleName":"Executive",
          "MenuList":null,
          "DefaultURL":null,
          "HasRole":false
       },
       { 
          "OrganisationID":0,
          "OrganisationName":null,
          "IsPrimary":false,
          "RoleId":6,
          "AccessId":-1,
          "RoleName":"Time Forecaster",
          "MenuList":null,
          "DefaultURL":null,
          "HasRole":false
       },
       { 
          "OrganisationID":0,
          "OrganisationName":null,
          "IsPrimary":false,
          "RoleId":7,
          "AccessId":-1,
          "RoleName":"Forecast Manager",
          "MenuList":null,
          "DefaultURL":null,
          "HasRole":false
       }
    ],
    "MDMAccess":[ 
       { 
          "OrganisationID":0,
          "OrganisationName":null,
          "IsPrimary":false,
          "RoleId":16,
          "AccessId":0,
          "RoleName":"CLIENT",
          "MenuList":null,
          "DefaultURL":null,
          "HasRole":false
       },
       { 
          "OrganisationID":0,
          "OrganisationName":null,
          "IsPrimary":false,
          "RoleId":17,
          "AccessId":0,
          "RoleName":"MEDIA OWNER",
          "MenuList":null,
          "DefaultURL":null,
          "HasRole":false
       }
    ]
 }
export { buyingOrganisation, userRole, Roles };

